[package]
name = "ssg"
version = "0.1.0"
edition = "2021"

[dependencies]
walkdir = "2"

markdown = "1.0.0-alpha.16"
markup = "0.15"

grass = "0.13.1"

serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
